# Documentation: https://github.com/codecov/support/wiki/codecov.yml

codecov:
  # CodeCov should only wait for CI's that run coverage tests
  # DAutoTester and auto-tester are not in the default list
  ci:
    - !travis
  bot: dlang-bot

coverage:
  precision: 3
  round: down
  range: 80...100

  status:
    # Learn more at https://codecov.io/docs#yaml_default_commit_status
    project: true
    patch: true
    changes: false

comment: false
