# Documentation: https://github.com/codecov/support/wiki/codecov.yml

codecov:
  # CodeCov should only wait for CI's that run coverage tests
  # DAutoTester and auto-tester are not in the default list
  ci:
    - !travis
  bot: dlang-bot

coverage:
  precision: 3
  round: down
  range: 80...100

  # Learn more at https://docs.codecov.io/docs/commit-status
  status:
    project: off
    patch:
      default:
        informational: true
    changes: off

comment: false
