sudo: false
os:
 - linux
language: d
d:
 - dmd-nightly
 - dmd-beta
 - dmd
 - ldc-beta
 - ldc

matrix:
  allow_failures:
    - d: ldc
    - d: dmd-beta # temporarily disabled due to https://issues.dlang.org/show_bug.cgi?id=17614
  include:
    - d: dmd-2.070.2 # the deployment compiler
      env: COVERAGE=true
      script:
        # https://issues.dlang.org/show_bug.cgi?id=13742
        - dub test --compiler=$DC --build=unittest-cov --build-mode=singleFile
      after_success:
        - bash <(curl -s https://codecov.io/bash)
