sudo: false
os:
 - linux
language: d
d:
 - dmd-nightly
 - dmd-beta
 - dmd
 - ldc-beta
 - ldc

script:
  # Tests are neither random- nor parallelizable atm., so use a --single serial thread.
  - dub test --compiler=$DC -- --single --trace

addons:
  apt:
    packages:
      - libevent-dev

matrix:
  include:
    - d: dmd-2.077.1 # the deployment compiler
      env: COVERAGE=true
      script:
        # Use --build-mode=singleFile to workaround https://issues.dlang.org/show_bug.cgi?id=13742
        # Tests are neither random- nor parallelizable atm., so use a --single serial thread.
        - dub test --compiler=$DC --build=unittest-cov --build-mode=singleFile -- --single --trace
      after_success:
        - bash <(curl -s https://codecov.io/bash)
  allow_failures:
   - d: dmd
   - d: dmd-nightly
   - d: dmd-beta
